# Compiles the emulator's own 16K ROM into the binary, so that a built
# xspeccy-mcp boots a machine on a host that has neither an Xpeccy configuration
# nor the Xpeccy sources it was built from. Without it the fallback is a path
# baked in at compile time (XSP_XPECCY_SRC), which does not survive being copied
# to another machine.
#
# The ROM is read from the upstream tree at configure time and written into the
# build directory. Nothing is copied into this repository, and upstream is not
# touched - the same rule the rest of the build follows.

# The ROM is somebody else's copyright (see THIRD_PARTY_NOTICES.md), so a binary
# that carries it is a binary that carries their work. That is the right default
# for a tool nobody can use without one, and it has to be possible to say no:
# with this OFF the executable holds no ROM and finds one at run time or not at
# all.
option(XSP_BUILTIN_ROM "Compile the emulator's 16K ROM into the executable" ON)

set(XSP_GENERATED_DIR "${CMAKE_BINARY_DIR}/generated")
set(_rom_header "${XSP_GENERATED_DIR}/xsp_rom_builtin.h")
set(_rom_file "${XPECCY_SRC}/conf/1982.rom")
file(MAKE_DIRECTORY "${XSP_GENERATED_DIR}")

if(NOT XSP_BUILTIN_ROM)
	file(WRITE "${_rom_header}"
		"// Generated by cmake/builtin_rom.cmake: XSP_BUILTIN_ROM is off, so this\n"
		"// binary carries no ROM and has to find one at run time.\n"
		"#pragma once\n")
	message(STATUS "Built-in ROM: off; the binary will need a ROM at run time")
elseif(EXISTS "${_rom_file}")
	file(SIZE "${_rom_file}" _rom_size)
	file(READ "${_rom_file}" _rom_hex HEX)
	string(REGEX REPLACE "(..)" "0x\\1," _rom_bytes "${_rom_hex}")
	string(REGEX REPLACE "((0x..,){16})" "\\1\n\t" _rom_bytes "${_rom_bytes}")
	file(WRITE "${_rom_header}"
		"// Generated by cmake/builtin_rom.cmake from ${_rom_file}\n"
		"// Do not edit, and do not commit: it lives in the build directory.\n"
		"#pragma once\n"
		"#define XSP_BUILTIN_ROM 1\n"
		"static const unsigned char kBuiltinRom[] = {\n\t${_rom_bytes}\n};\n")
	message(STATUS "Built-in ROM: ${_rom_file} (${_rom_size} bytes)")
else()
	file(WRITE "${_rom_header}"
		"// Generated by cmake/builtin_rom.cmake: no ROM found at\n"
		"// ${_rom_file}\n"
		"#pragma once\n")
	message(WARNING
		"no 1982.rom under ${XPECCY_SRC}/conf - the binary will boot a machine "
		"only where it can find a ROM at run time (--config, or those sources)")
endif()
